apiVersion: v1
kind: Secret
metadata:
  name: cage-secrets
  namespace: cage-system
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME_GENERATE_WITH_openssl_rand_base64_32"
  admin-token: "CHANGE_ME_GENERATE_WITH_openssl_rand_base64_32"
